### ISSUE TITLE
permission denied on Docker Compose up

### ISSUE THREAD

**Issue by Kleinendorst** [jirkapinkas/spring-boot-postgresql-docker-compose#1]
While trying to run the project, I get the following error after entering `docker-compose up`:

`ERROR: for app  Cannot start service app: oci runtime error: container_linux.go:247: starting container process caused "exec: \"./start.sh\": permission denied"
ERROR: Encountered errors while bringing up the project.`

**Comment by jirkapinkas** [comment]
Which OS (Windows, Linux, Mac) do you use and which Docker version?

**Comment by Kleinendorst** [comment]
I'm using Docker for Windows on Windows. Version: `17.03.1-ce-win5 (10743)` - which is from the stable channel.

As far as I understand the shell scripts are copied to the alpine vm, which is installed with Docker for Windows?

**Comment by Kleinendorst** [comment]
Hmm, this issue is present on all containers. Most likely not an issue with this Github repo, I'll mark this issue as resolved!
